// Generated by aaa string tool. Do _not_ modify.

import Foundation

// swiftlint:disable line_length
public struct Strings {

    public struct Network {
        static let errorGeneric = Strings.localized("network_error_generic", value: "An error has occurred.")
        static let errorLoadingFailed = Strings.localized("network_error_loading_failed", value: "Could not load data. (Code %1$@)")
        static let errorNoConnection = Strings.localized("network_error_no_connection", value: "No network connection. Please try again later.")
        static let errorPostingFailed = Strings.localized("network_error_posting_failed", value: "Data could not be transferred. (Code %1$@)")
        static let errorWrongCredentials = Strings.localized("network_error_wrong_credentials", value: "You entered an incorrect username or a wrong password. Please try again.")
        static let errorActionDisabled = Strings.localized("network_error_action_disabled", value: "The Action is already running.")
        static let errorFirestoreSetData = Strings.localized("firestore_error_setData", value: "Error during firestore saving.")
    }

    public struct Classification {
        static let noResults = Strings.localized("classification_results_notfound", value: "Classification results not found.")
        static let preProcessingFailedTitle = Strings.localized("classification_preprocessing_failed.title", value: "Processing Error")
        static let preProcessingFailedDescription = Strings.localized("classification_preprocessing_failed.description", value: "Image Preprocessing failed.")
    }

    public struct TabBarViewControllter {
        static let flickrTitle = Strings.localized("tabbarcontroller_title_flickr", value: "Flickr")
        static let savesTitle = Strings.localized("tabbarcontroller_title_saves", value: "Saves")
    }

    public struct ImagesViewController {
        static let firestoreTitle = Strings.localized("images_realm_title", value: "Database Image Search")
        static let flickrTitle = Strings.localized("images_flickr_title", value: "Flirckr Image Search")
        static let emptyViewDescription = Strings.localized("emtpy_view_description", value: "Enter tags into the search bar to find images. At the moment there are no pictures found.")
    }

    public struct ProcessingViewController {
        static let titlePickedImage = Strings.localized("processing_title_pickedimage", value: "Picked Image")
        static let startButtonTitle = Strings.localized("processing_title_startbutton", value: "Start")
        static let reStartButtonTitle = Strings.localized("processing_title_restartbutton", value: "Restart")
    }

    public struct EnableSettingCell {
        static let modelSizeDescription = Strings.localized("settings_modelsize_description", value: "Preprocess image to model size")
        static let grayscaleDescription = Strings.localized("settings_grayscale_description", value: "Preprocess image to grayscale")
        static let showResizedImagesDescription = Strings.localized("settings_resizedimages_description", value: "Show the resized images")
    }

    public struct Alert {
        static let ok = Strings.localized("Shared.buttons.ok", value: "OK")
        static let confirm = Strings.localized("Shared.buttons.confirm", value: "Confirm")
        static let cancel = Strings.localized("Shared.buttons.cancel", value: "Cancel")
        static let save = Strings.localized("Shared.buttons.save", value: "Save")
        static let discard = Strings.localized("Shared.buttons.discard", value: "Discard")
        static let delete = Strings.localized("Shared.buttons.delete", value: "Delete")
        static let settings = Strings.localized("Shared.buttons.settings", value: "Settings")
        static let library = Strings.localized("Shared.titles.library", value: "Library")
        static let camera = Strings.localized("Shared.titles.camera", value: "Camera")
        static let assume = Strings.localized("Shared.buttons.assume", value: "Assume")
        static let accessPermittedTitle = Strings.localized("Shared.access.permitted.title", value: "Access permitted")
        static let accessPermittedSubTitle = Strings.localized("Shared.access.permitted.subtitle", value: "Enable the permission in your settings to use this feature.")
    }

    // settings this closure allows you to use a custom localization provider, such as OneSky over-the-air
    // by default, NSLocalizedString will load the strings from the main bundle's Localizable.strings file
    public static var customLocalizationClosure: ((String, String?, Bundle, String, String) -> String)?

    public static func localized(_ key: String, tableName: String? = nil, bundle: Bundle = Bundle.main, value: String, comment: String = "") -> String {
        if let closure = Strings.customLocalizationClosure {
            return closure(key, tableName, bundle, value, comment)
        } else {
            return NSLocalizedString(key, tableName: tableName, bundle: bundle, value: value, comment: comment)
        }
    }
}
